feat(opreator): add volcengine metadata service
ruicao93/cilium pull request #5
Opened 2024-03-14 14:17 UTC by dakehero

2024-03-15 02:42 UTC, ruicao93 commented on pkg/volcengine/api/metadata.go
> +	"time"
参考其他文件，time替换成 cilium time wrapper

2024-03-15 02:42 UTC, ruicao93 commented on pkg/volcengine/api/metadata.go
> +func (client *Metadata) GetNICInfo(mac string) (*types.NICInfo, error) {
nic -> interface

2024-03-15 02:46 UTC, dakehero commented on pkg/volcengine/api/metadata.go
> +	"time"
OK, 但是这里只用到了类型和常量，应该是相同的

2024-03-15 03:59 UTC, ruicao93 approved these changes

2024-03-15 04:04 UTC, ruicao93 requested changes

2024-03-15 04:04 UTC, ruicao93 commented on pkg/volcengine/api/metadata.go
> +func NewEC2Metadata() *Metadata {
EC2?

2024-03-18 05:50 UTC, ruicao93 approved these changes

2024-03-18 05:52 UTC, merged